//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public int IdOrden { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string DescripcionServicio { get; set; }
        public double CostoTotal { get; set; }
        public string TipoServicio { get; set; }
        public int IdVehiculo { get; set; }
        public int IdAdministrador { get; set; }
        public int IdMecanico { get; set; }
        public string Estado { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Mecanico Mecanico { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
