//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Orden = new HashSet<Orden>();
        }
    
        public int IdVehiculo { get; set; }
        public int Año { get; set; }
        public string Color { get; set; }
        public string Placa { get; set; }
        public string Estado { get; set; }
        public bool Eliminado { get; set; }
        public int IdTipoVehiculo { get; set; }
        public int IdMarca { get; set; }
        public int IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Orden { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
